### ISSUE TITLE
Missing pins with TI datasheets

### ISSUE THREAD

**Issue by metafex** [Robotips/uConfig#4]
I tried to generate libs from a few TI datasheets, but it misses some pins:

- http://www.ti.com/lit/ds/symlink/cc1352p.pdf package on page 6.
- http://www.ti.com/lit/ds/symlink/cc1125.pdf the package on page 5 and the pin description table on page 6 miss different pins when extracting.
 - http://www.ti.com/lit/ds/symlink/tms320f280049c.pdf pages 13-16 is another one I randomly tested and where it fails to detect most or all of the pins.

For e.g. the MSP430 MCU datasheets it works like a charm and detects all the pins, it might have to do with the departments using different styling on the datasheets.

**Comment by sebcaux** [comment]
Thanks for the issue !
I partially fix it :

* cc1352p.pdf : The first 4 pins and others are well detected. The "long pin filter" removed it because they have more than 10 chars and does not contain "/". I added "_" for ST style datasheet.
* cc1125.pdf : In the table p6, a label is very close and the PDF parser tell me it's the next part of the text, so he merge it.
* tms320f280049c.pdf : Unfortunately, the PDF seems to be malformed, my pdf reader is unable to read some vertical pins. I can't fix it.

I also fix the potential page with schematic detector.

>  it might have to do with the departments using different styling on the datasheets

Good idea, it could be a different repository with well worked datasheet and non working datasheet with the status and the reason. I started to do that with only few datasheets in the autotest directory.

Thanks to add a star if you love it.

**Comment by metafex** [comment]
Thank you very much! The tms320f280049c.pdf being malformed explains why it doesn't detect much.

**Comment by sebcaux** [comment]
tms320f280049c.pdf is finally fixed, it was a problem of alignment detection for small pin name and long pin filter ("," added as separator)

**Comment by rigid** [comment]
This [datasheet](http://www.ti.com/lit/ds/symlink/cd74hct4094.pdf) also gets processed fine but pins 11, 12 and 13 are missing.
